.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2014 Donovan Kolbly <donovan@rscheme.org>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH HEXPLORE 6 "March  1, 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
hexplore \- A game of exploration and discovery in a hex world
.SH SYNOPSIS
.B hexplore
.RI [ -c HOST [: PORT ]] [ -P
.br
.SH DESCRIPTION
This manual page documents briefly the
.B hexplore
game.
.PP
.B hexplore
is a game of exploration, creation and discovery,
set in a large shared world made up of hexagonal tiles.
It's primary purpose is to make your video card hot.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-c, \-\-connect
Server to connect to.  Hostname optionally followed by
a colon and a port number.
.TP
.B \-v, \-\-version
Show version of program.
.SH SEE ALSO
.BR hexplore-server (6).
